org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=daemon
kotlin.incremental=true
org.gradle.workers.max=3
